/**
 * Voice prompts bundled with the app so they play offline in English and Hindi,
 * independent of whether the device has a Hindi text-to-speech voice.
 * Clips are generated by scripts/gen-audio.mjs and precached by the service worker.
 */
import type { ActionKey, CareStateKey } from '../db/types';
import type { Lang } from '../i18n';

const ACTIONS: ActionKey[] = [
  'complete_details', 'send_referral', 'confirm_referral', 'send_info', 'find_alternative', 'confirm_appointment',
  'remind_patient', 'check_attendance', 'visit_home', 'reschedule', 'record_outcome', 'plan_follow_up', 'resolve_conflict', 'none',
];
const STATES: CareStateKey[] = [
  'incomplete', 'not_sent', 'awaiting_facility', 'info_requested', 'declined', 'accepted_no_appt', 'scheduled',
  'appt_passed_unknown', 'not_attended', 'attended_outcome_unknown', 'follow_up_required', 'closed',
];

/** Message keys that have a bundled audio clip. */
export const BUNDLED_PROMPT_KEYS: string[] = [
  ...ACTIONS.map((a) => `action.${a}`),
  ...STATES.map((s) => `careState.${s}`),
  'reason.youDecide',
  'intel.suggested',
  'intel.careState',
  'status.savedLocally',
  'followup.saved',
];

export function clipUrl(lang: Lang, key: string): string {
  return `${import.meta.env.BASE_URL}audio/${lang}/${key.replace(/\./g, '_')}.m4a`;
}
